name: snaptik
description: "TikTok Downloader."
publish_to: 'none'
version: 2.0.1+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core & Utilities
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  # get_it: ^8.0.3
  cached_network_image: ^3.4.1
  open_filex: ^4.7.0
  uuid: ^4.5.1
  device_info_plus: ^11.3.0
  file_saver: ^0.2.14

  # UI & UX
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17

  # Media
  video_player: ^2.9.5
  chewie: ^1.11.1
  audioplayers: ^6.4.0
  photo_view: ^0.15.0

  # Monetization
  google_mobile_ads: ^5.3.1
  purchases_flutter: ^8.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

# For App Icon Generation
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/images/app_icon.png"
  image_path_android: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21

# For Native Splash Screen Generation
flutter_native_splash:
  color: "#FFFFFF" # Light mode splash background
  color_dark: "#121212" # Dark mode splash background
  image: assets/images/splash_logo.png # Create this image (light mode)
  image_dark: assets/images/splash_logo_dark.png # Create this image (dark mode)
  android_12:
    image: assets/images/splash_logo_dark_android12_padded.png
    image_dark: assets/images/splash_logo_dark_android12_padded.png
    color: "#FFFFFF"
    color_dark: "#121212"
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/